#!/bin/bash

usage="Usage: gaia [ info | stake | latest | dust ] \n \n
	info: Check basic info. \n
	stake: Enables staking; Passes password without storing it in memory. \n
	latest: Compares latest block with the GaiacoinNL hosted block explorer. \n
	dust: Prunes dust from wallet. Dust is defined as less than .0001GAIA. Requires jq. \n"

gaiac='/usr/local/bin/gaiacoin-cli -datadir=/var/lib/.gaiacoin/'

case $1 in

info )
	$gaiac getwalletinfo | egrep "balance|staked_balance|txcount|unconfirmed_balance|immature_balance|total_balance";
	$gaiac getnetworkinfo | egrep "subversion|connections";
	$gaiac getinfo | egrep "blocks";
	$gaiac getblockchaininfo | egrep "best";
	$gaiac getstakinginfo | egrep "enabled|staking|netstakeweight|expectedtime";
;;	

stake )
	echo 'enter Gaiacoin Password'
	read -s GAIAPW
	$gaiac walletpassphrase $GAIAPW 99999999 true
	GAIAPW=null
;;

latest )
	latest=$($gaiac  getblockcount) && \
	    blacksight=$(curl -s https://node.gaiacoin.io/insight-api/block-index/$latest? |  cut -d '"' -f4) && \
	    gaiacoin=$($gaiac  getblockhash $latest) && \
	    diff -sy --label Local <(echo $gaiacoin) --label Explorer <(echo $blacksight)
;;

dust )
	IFS=$'\n';

	 /usr/local/bin/gaiacoin-cli -datadir=/var/lib/.gaiacoin/ listtransactions "*" 99999 | jq -r '.[] | select(.category != "send") | select(.amount < .0001) | .txid' | uniq >txid.txt

	while read line; do
	        echo $line 
	        /usr/local/bin/gaiacoin-cli -datadir=/var/lib/.gaiacoin/ removeprunedfunds $(echo $line)
	done < "txid.txt"
;;

*)
    echo -e $usage
;;	

esac
